---
- block:
    - set_fact:
        service: '{{ role_name }}'

    - import_role:
        name: services
        tasks_from: prepare

    - name: Copy config
      copy:
        src: 'config.yml'
        dest: '{{ service_path }}/config.yml'
      notify:
        - restart_main_service

    - name: Copy icons
      # copy is really slow with directories
      ansible.posix.synchronize:
        src: 'icons/'
        dest: '{{ service_path }}/icons'
      notify:
        - restart_main_service

    - import_role:
        name: services
        tasks_from: uplift
  tags: dashy
