---
- block:
    - set_fact:
        service: '{{ role_name }}'

    - import_role:
        name: services
        tasks_from: prepare

    - name: Generate ghost config
      template:
        src: 'ghost-config.json.j2'
        dest: '{{ service_path }}/ghost-config.json'
      notify:
        - restart_main_service

    - name: Generate nginx config
      template:
        src: 'nginx.conf.j2'
        dest: '{{ service_path }}/nginx.conf'
      notify:
        - restart_main_service

    - import_role:
        name: services
        tasks_from: uplift
  tags: rpgbasement