---
- set_fact:
    service: '{{ role_name }}'
  tags: ['jellyfin', 'jellyfin-backup']

- name: Include vault
  include_vars: vault.yml
  tags: ['jellyfin', 'jellyfin-backup']

- import_role:
    name: jellyfin
    tasks_from: backup
  tags: ['never', 'jellyfin-backup']

- block:
    - set_fact:
        service: '{{ role_name }}'

    - import_role:
        name: services
        tasks_from: prepare

    - import_role:
        name: services
        tasks_from: uplift
  tags: jellyfin
