---
- hosts: edge
  tasks:
    - import_role:
        name: jenkins
        tasks_from: backup
  tags: jenkins

- hosts: edge
  tasks:
    - import_role:
        name: paperless
        tasks_from: backup
  tags: paperless

- hosts: edge
  tasks:
    - import_role:
        name: nextcloud
        tasks_from: backup
  tags: nextcloud

- hosts: edge
  tasks:
    - import_role:
        name: kanboard
        tasks_from: backup
  tags: kanboard

- hosts: edge
  tasks:
    - import_role:
        name: etherpad
        tasks_from: backup
  tags: etherpad

- hosts: edge
  tasks:
    - import_role:
        name: rpgbasement
        tasks_from: backup
  tags: rpgbasement

- hosts: edge
  tasks:
    - import_role:
        name: ttrss
        tasks_from: backup
  tags: ttrss
