---
dns:
  grafana: mon.{{ lan }}
  alertmanager: alerts.{{ lan }}
  prometheus: prom.{{ lan }}
exposed_port:
  grafana: 3000
  alertmanager: 9093
  prometheus: 9090

grafana:
  version: "8.5.9"
  username: admin
  password: "{{ vault_grafana_password }}"
alertmanager:
  version: "v0.24.0"
  discord_webhook: "{{ vault_discord_webhook }}"
prometheus:
  version: "v2.37.0"
