---
domain: testchamber.one
lan: 'lan.{{ domain }}'
zfs_pool: tank

ignored_users:
  - nobody # default linux user
  - ceph # proxmox
  - wunder # me
  - ci # ci

public_ip: '{{ vault_public_ip }}'
ansible_become_password: '{{ vault_ansible_become_password }}'
cf_api_token: '{{ vault_cf_api_token }}'
registry:
  url: reg.{{ lan }}
  pass: '{{ vault_registry.pass }}'
