---
- name: Shutdown main {{ service }} service
  shell: 'docker service scale {{ service }}_{{ service }}=0'

- import_role:
    name: backup
    tasks_from: zfs-rsync
  vars:
    source_volume: '{{ service }}_app'
    backup_dataset: '/{{ zfs_pool }}/{{ zfs.app }}'

- import_role:
    name: backup
    tasks_from: zfs-rsync
  vars:
    source_volume: '{{ service }}_plugins'
    backup_dataset: '/{{ zfs_pool }}/{{ zfs.plugins }}'

- name: Start main {{ service }} service
  shell: 'docker service scale {{ service }}_{{ service }}=1'

- import_role:
    name: backup