---
- block:
    - name: Get existing users
      shell: "getent passwd | awk -F: '$3 > 1000 {print $1}'"
      changed_when: false
      register: users

    - name: Cleanup users
      user:
        name: '{{ item }}'
        state: absent
        remove: true
        force: true
      loop: '{{ users.stdout_lines }}'
      when: item not in ignored_users

    - name: Disable password ssh login
      shell: '{{ item }}'
      loop:
        - "sed -i '/PasswordAuthentication /d' /etc/ssh/sshd_config"
        - "echo 'PasswordAuthentication no' | tee -a /etc/ssh/sshd_config"

    - name: Disable interactive root login
      shell: '{{ item }}'
      loop:
        - "sed -i '/PermitRootLogin /d' /etc/ssh/sshd_config"
        - "echo 'PermitRootLogin prohibit-password' | tee -a /etc/ssh/sshd_config"

    - name: Reload sshd config
      service:
        name: sshd
        state: reloaded

  become: true
