---
- block:
    - name: Get existing users
      shell: "getent passwd | awk -F: '$3 > 1000 {print $1}'"
      changed_when: false
      register: users

    - name: Cleanup users
      user:
        name: '{{ item }}'
        state: absent
        remove: true
        force: true
      loop: '{{ users.stdout_lines }}'
      when: item not in ignored_users

    - name: Disable password ssh login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication'
        line: 'PasswordAuthentication no # managed by ssh_keys'

    - name: Disable interactive root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PermitRootLogin'
        line: 'PermitRootLogin without-password # managed by ssh_keys'

    - name: Disable X forwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'X11Forwarding'
        line: 'X11Forwarding no # managed by ssh_keys'

    - name: Disable reverse tunneling
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'GatewayPorts'
        line: 'GatewayPorts no # managed by ssh_keys'

    - name: Reload sshd config
      service:
        name: sshd
        state: reloaded

  become: true
