---
- name: Shutdown main {{ service }} service
  shell: 'docker service scale {{ service }}_{{ service }}=0'

- name: Dump mysql db
  shell: "docker exec $(docker ps -q --filter 'name={{ service }}_db') sh -c 'mysqldump -p$MYSQL_ROOT_PASSWORD nextcloud > /dump/nextcloud.dump'"
  # restore: mysql -p$MYSQL_ROOT_PASSWORD nextcloud < /dump/nextcloud.dump

- import_role:
    name: backup
    tasks_from: zfs-rsync
  vars:
    source_volume: '{{ service }}_app'
    backup_dataset: '/{{ zfs_pool }}/{{ zfs.app }}'

- name: Start main {{ service }} service
  shell: 'docker service scale {{ service }}_{{ service }}=1'

- import_role:
    name: backup
