---
- block:
    - name: Generate previews
      shell: |
        {% raw %}EXEC_FLAGS="-u 33" /opt/homelab/swarm-exec.sh nextcloud_nextcloud ./occ preview:pre-generate{% endraw %}
      become: true
      register: output

    - debug: var=output.stdout_lines

    - name: Rescan storage
      shell: |
        {% raw %}EXEC_FLAGS="-u 33" /opt/homelab/swarm-exec.sh nextcloud_nextcloud ./occ files:scan --all{% endraw %}
      become: true
      register: output

    - debug: var=output.stdout_lines

    - name: Healthcheck
      uri:
        url: '{{ healthcheck_url }}'
