---
- block:
    - name: Generate previews
      shell: |
        {% raw %}docker exec -u 33 $(docker ps -q --filter "name=nextcloud_nextcloud"){% endraw %} {{ item }}
      loop:
        - ./occ preview:pre-generate
        - ./occ files:scan --all
        - ./occ files:scan-app-data
      register: output

    - debug: var=output.stdout_lines

    - name: Healthcheck
      uri:
        url: '{{ maintenance_healthcheck_url }}'
