---
- set_fact:
    service: '{{ role_name }}'
  tags: ['nextcloud', 'nextcloud-backup']

- name: Include vault
  include_vars: vault.yml
  tags: ['nextcloud', 'nextcloud-backup']

- import_role:
    name: nextcloud
    tasks_from: backup
  tags: ['never', 'nextcloud-backup']

- import_role:
    name: nextcloud
    tasks_from: maintenance
  tags: ['never', 'nextcloud-maintenance']

- block:
    - import_role:
        name: services
        tasks_from: prepare

    - import_role:
        name: services
        tasks_from: uplift
  tags: nextcloud
