---
- set_fact:
    service: '{{ role_name }}'
  tags: ['nextcloud', 'nextcloud-backup']

- block:
    - import_role:
        name: services
        tasks_from: prepare

    - import_role:
        name: services
        tasks_from: uplift
  tags: nextcloud

- import_role:
    name: services
    tasks_from: backup
  tags: ['never', 'nextcloud-backup']