---
- block:
    - set_fact:
        service: '{{ role_name }}'

    - import_role:
        name: services
        tasks_from: prepare

    - name: Build blog
      shell:
        cmd: '{{ item }}'
        chdir: '{{ role_path }}/files'
      loop:
        - docker run --rm -u 1000:1000 -v $PWD:/src klakegg/hugo
      delegate_to: localhost

    - name: Copy site
      # copy is really slow with directories
      ansible.posix.synchronize:
        src: 'public/'
        dest: '{{ service_path }}/site'
      notify:
        - restart_main_service

    - import_role:
        name: services
        tasks_from: uplift
  tags: blog
