---
- set_fact:
    service: '{{ role_name }}'
  tags: ['qbittorrent', 'qbittorrent-backup']

- block:
    - import_role:
        name: services
        tasks_from: prepare

    - import_role:
        name: services
        tasks_from: uplift
  tags: qbittorrent

- import_role:
    name: services
    tasks_from: backup
  tags: ['never', 'qbittorrent-backup']
