---
- block:
    - set_fact:
        service: '{{ role_name }}'

    - import_role:
        name: services
        tasks_from: prepare

    - name: Generate config
      template:
        src: 'configuration.yml.j2'
        dest: '/{{ zfs_pool }}/{{ service }}/configuration.yml'
      delegate_to: "{{ groups['nas'][0] }}"
      become: true
      notify:
        - restart_main_service

    - name: Copy users database
      copy:
        src: 'users_database.yml'
        dest: '/{{ zfs_pool }}/{{ service }}/users_database.yml'
      delegate_to: "{{ groups['nas'][0] }}"
      become: true
      notify:
        - restart_main_service

    - import_role:
        name: services
        tasks_from: uplift
  tags: authelia
