---
- block:
    - set_fact:
        service: '{{ role_name }}'

    - name: Include vault
      include_vars: vault.yml

    - import_role:
        name: services
        tasks_from: prepare

    - name: Create config directory
      file:
        path: '{{ service_path }}/config'
        state: directory

    - name: Generate config
      template:
        src: 'configuration.yml.j2'
        dest: '{{ service_path }}/config/configuration.yml'
      become: true
      notify:
        - restart_main_service

    - name: Copy users database
      copy:
        src: 'users_database.yml'
        dest: '{{ service_path }}/config/users_database.yml'
      become: true
      notify:
        - restart_main_service

    - import_role:
        name: services
        tasks_from: uplift
  tags: authelia
