---
- block:
    - set_fact:
        service: '{{ role_name }}'

    - import_role:
        name: services
        tasks_from: prepare

    - name: Build resume
      shell:
        cmd: npm ci && npm run resume -- export dist/index.html --theme full
        chdir: '{{ role_path }}/files'
      delegate_to: localhost

    - name: Copy site
      # copy is really slow with directories
      ansible.posix.synchronize:
        src: 'dist/'
        dest: '{{ service_path }}/site'
      notify:
        - restart_main_service

    - import_role:
        name: services
        tasks_from: uplift
  tags: cv
