---
- import_role:
    name: backup
    tasks_from: zfs-rsync
  vars:
    source_volume: '{{ service }}_config'
    backup_dataset: '/{{ zfs_pool }}/{{ zfs.config }}'

  # rsync -avz --progress --stats --delete $(docker volume inspect --format '{{ .Mountpoint }}' jenkins_config)/ {{ backup_dir }}/

- import_role:
    name: backup
