---
- name: Shutdown main {{ service }} service
  shell: 'docker service scale {{ service }}_{{ service }}=0'

- name: Dump data
  shell: "docker exec $(docker ps -q --filter 'name={{ service }}_db') sh -c 'pg_dump -U djangouser -Fc djangodb > /dump/{{ service }}.dump'"
  # restore: dropdb -U djangouser djangodb && pg_restore -U djangouser -C -d postgres /dump/tandoor.dump

- import_role:
    name: backup
    tasks_from: zfs-rsync
  vars:
    source_volume: '{{ service }}_mediafiles'
    backup_dataset: '/{{ zfs_pool }}/{{ zfs.mediafiles }}'

- import_role:
    name: backup
    tasks_from: zfs-rsync
  vars:
    source_volume: '{{ service }}_staticfiles'
    backup_dataset: '/{{ zfs_pool }}/{{ zfs.staticfiles }}'

- name: Start main {{ service }} service
  shell: 'docker service scale {{ service }}_{{ service }}=1'

- import_role:
    name: backup
