---
- name: Shutdown main {{ service }} service
  shell: "docker service scale {{ service }}_{{ service }}=0"

- name: Dump postgres db
  shell: "docker exec $(docker ps -q --filter 'name={{ service }}_postgres') sh -c 'pg_dump -U etherpad -Fc etherpad > /dump/etherpad.dump'"

  # restore: dropdb -U etherpad etherpad && pg_restore -U etherpad -C -d postgres /dump/etherpad.dump
- import_role:
    name: backup
    tasks_from: zfs-rsync
  vars:
    source_volume: "{{ service }}_app"
    backup_dataset: "/{{ zfs_pool }}/{{ zfs.app }}"

- name: Start main {{ service }} service
  shell: "docker service scale {{ service }}_{{ service }}=1"

- import_role:
    name: backup
