---
http:
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`pve1.lan.testchamber.one`)"
      middlewares:
        - default-headers
      tls: {}
      service: proxmox
    syncthing:
      entryPoints:
        - "https"
      rule: "Host(`sync.lan.testchamber.one`)"
      middlewares:
        - default-headers
      tls: {}
      service: syncthing
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.5.10:8006"
        passHostHeader: true
    syncthing:
      loadBalancer:
        servers:
          - url: "http://192.168.5.113:8384"
        passHostHeader: true

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "192.168.0.0/16"
          - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers
