---
- block:
    - set_fact:
        service: "{{ role_name }}"

    - import_role:
        name: services
        tasks_from: prepare

    - name: Generate ntfy config
      template:
        src: "server.yml.j2"
        dest: "{{ service_path }}/server.yml"
      notify:
        - restart_main_service

    - import_role:
        name: services
        tasks_from: uplift
  tags: ntfy
