---
- name: Shutdown main {{ service }} service
  shell: 'docker service scale {{ service }}_{{ service }}=0'

- name: Dump postgres db
  shell: "docker exec $(docker ps -q --filter 'name={{ service }}_postgres') sh -c 'pg_dump -U postgres -Fc {{ service }} > /dump/{{ service }}.dump'"

  # restore: pg_restore -U postgres -C -d postgres /dump/ttrss.dump

- name: Start main {{ service }} service
  shell: 'docker service scale {{ service }}_{{ service }}=1'

- import_role:
    name: backup