---
- set_fact:
    service: '{{ role_name }}'
  tags: ['ttrss', 'ttrss-backup']

- block:
    - import_role:
        name: services
        tasks_from: prepare

    - import_role:
        name: services
        tasks_from: uplift
  tags: ttrss

- import_role:
    name: services
    tasks_from: backup
  tags: ['never', 'ttrss-backup']