---
- set_fact:
    service: '{{ role_name }}'
  tags: ['ttrss', 'ttrss-backup']

- name: Include vault
  include_vars: vault.yml
  tags: ['ttrss', 'ttrss-backup']

- import_role:
    name: ttrss
    tasks_from: backup
  tags: ['never', 'ttrss-backup']

- block:
    - import_role:
        name: services
        tasks_from: prepare

    - import_role:
        name: services
        tasks_from: uplift
  tags: ttrss
