---
- set_fact:
    service: '{{ role_name }}'
  tags: ['syncthing', 'syncthing-backup']

- block:
    - import_role:
        name: services
        tasks_from: prepare

    - import_role:
        name: services
        tasks_from: uplift
  tags: syncthing

- import_role:
    name: services
    tasks_from: backup
  tags: ['never', 'syncthing-backup']
