---
- name: Set {{ service }} dir path
  set_fact:
    service_path: '{{ root_path }}/{{ service }}'

- name: Create {{ service }} directory
  file:
    path: '{{ service_path }}'
    state: directory
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
  become: true

- name: Create ZFS datasets for {{ service }}
  zfs:
    name: '{{ zfs_pool }}/{{ item.value }}'
    state: present
    extra_zfs_properties:
      sharenfs: 'rw=@192.168.0.0/16,no_root_squash'
  loop: '{{ zfs | dict2items }}'
  when: zfs is defined
  become: true
  run_once: true
  delegate_to: "{{ groups['nas'][0] }}"

- name: Create A records for {{ service }}
  cloudflare_dns:
    zone: '{{ domain }}'
    record: '{{ item.value }}'
    type: A
    value: '{{ public_ip }}'
    proxied: true
    account_email: cloudflare@{{ domain }}
    account_api_key: '{{ cf_api_token }}'
  loop: '{{ dns | dict2items }}'
  when: 'lan not in item.value and domain in item.value'
  run_once: true
  delegate_to: localhost
