---
- name: Set {{ service }} dir path
  set_fact:
    service_path: '{{ root_path }}/{{ service }}'

- name: Create {{ service }} directory
  file:
    path: '{{ service_path }}'
    state: directory
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
  become: true

# create zfs datasets
# zfs create -o sharenfs="rw=@192.168.0.0/16,no_root_squash" tank/SERVICE
